name: Run Selenium TestNG Tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Get your code from repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Run tests with Maven
    - name: Run tests
      run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
